### PR TITLE
Section title

### PR DESCRIPTION
**Pull request by kallepronk**

### CODE REVIEW

**Comment by 1SvenHansen** [comment]
Title component looks and works good.
Could you by any chance add it on the partners page as well? 
image

**Comment by 1SvenHansen** [comment]
Could you by any chance add it to the partners page as well?
image

**Review by BartvanEijkelenburg — CHANGES_REQUESTED** [review]
It looks good, 

however the component is made within mind that each page does contain the scss for:  text-align: center. please do not use text align center, it break things later on, text align center is used for centering a paragraph's text. not centering components. Use flexbox for that.

**Review by BartvanEijkelenburg — APPROVED** [review]
MIND THE FACT THAT TEXT ALIGN CENTER NEEDS TO BE GONE SOON.

**Pull request merged**
